/**
 * MedHit Task Manager - Seed Script Realista
 * Autor: MedHit Integrações & Automações
 * Gera dados completos para Marketing e Automação com humanos e agentes de IA
 */

export const seedData = {
  workspace: {
    name: "MedHit",
    slug: "medhit",
    settings: {
      theme: "dark",
      aiEnabled: true,
      defaultLanguage: "pt-BR",
    },
  },
  members: [
    {
      name: "Lucca Lagana",
      email: "lucca.guidorizzi@medhit.com.br",
      role: "owner" as const,
      password: "x32kd58",
      mcpToken: "medtask_user_lucca_x32kd58_sec99",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca",
    },
    {
      name: "Thiago Ghiraldini",
      email: "thiago.ghiraldini@medhit.com.br",
      role: "owner" as const,
      password: "x32kd58",
      mcpToken: "medtask_user_thiago_sec100",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Thiago",
    },
  ],
  agents: [
    {
      name: "MedCopy IA",
      slug: "medcopy-ia",
      role: "Copywriter & Estrategista de Conteúdo",
      model: "gemini-2.0-flash",
      avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=MedCopy",
      description: "Especialista em redação persuasiva para médicos e cursos de saúde.",
      systemPrompt: "Você é um copywriter de elite da MedHit especializado no mercado médico.",
      allowedTools: ["generate_copy", "suggest_headlines", "review_seo"],
      status: "active" as const,
    },
    {
      name: "n8n Auditor IA",
      slug: "n8n-auditor-ia",
      role: "Auditor e Engenheiro de Integrações",
      model: "gemini-2.0-flash",
      avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=n8nAuditor",
      description: "Monitora webhooks, analisa nós n8n e verifica integridade de payloads.",
      systemPrompt: "Você audita e valida fluxos do n8n para a MedHit.",
      allowedTools: ["inspect_workflow", "validate_payload", "report_incident"],
      status: "active" as const,
    },
    {
      name: "Triage Bot IA",
      slug: "triage-bot-ia",
      role: "Triagem Inteligente de Demandas",
      model: "gemini-2.0-flash",
      avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=TriageBot",
      description: "Classifica formulários recebidos e encaminha para a squad correta.",
      systemPrompt: "Você analisa solicitações e sugere prioridade, prazos e responsáveis.",
      allowedTools: ["categorize_request", "assign_team", "estimate_effort"],
      status: "active" as const,
    },
  ],
  areas: [
    {
      name: "Campanhas Marketing",
      slug: "campanhas-marketing",
      description: "Eixo principal de campanhas de marketing, lançamentos e simulados educacionais.",
      icon: "megaphone",
      color: "#ec4899",
      folders: [
        "Simulado Intensivo Reta Final 1F",
        "Recursos Gerais 2F",
        "Masterclass Ultima Semana 1F",
        "Masterclass Plano Perfeito 2F",
        "Copa Mundo Revalida",
        "Recursos Gerais 1F",
        "Maratona da Aprovação",
        "Imersão Gabaritando 1F",
        "Simulado Nacional 2026.2",
        "Pré-venda Recursos 2F",
        "Masterclass Checklist Gabaritado 2F",
        "Masterclass Virada Final 1F",
        "MR Day Online 1F",
        "Aula de Revisão Final 1F",
        "Preparatórios Revalida 1F e 2F",
        "Masterclass Checklist Gabaritado 2F - 2ª rodada",
        "Simulado Revalida Reta Final 1F",
        "Premonições 1F",
        "Simulado TRI 1F",
        "Porta de Prova 2026",
        "Intensivo Presencial 1F 2027.1",
        "Masterclass Plano Perfeito 2F - setembro",
        "Medtask 30 Dias Grátis - Prova Prática 2F",
        "Live Recursos Gerais 1F - setembro",
        "Revalida PASS Pré-Venda",
      ],
      projects: [
        {
          id: "proj-campanhas-01",
          workspaceId: "ws-medhit-001",
          areaId: "area-1",
          name: "Campanhas Marketing",
          slug: "campanhas-marketing",
          description: "Quadro e esteira geral de campanhas do ClickUp",
          icon: "megaphone",
          color: "#ec4899",
          methodology: "kanban" as const,
          statuses: [
            { id: "st-camp-1", workspaceId: "ws-medhit-001", projectId: "proj-campanhas-01", name: "A Fazer", color: "#94a3b8", position: 1, category: "todo" as const },
            { id: "st-camp-2", workspaceId: "ws-medhit-001", projectId: "proj-campanhas-01", name: "Em Andamento", color: "#38bdf8", position: 2, category: "in_progress" as const },
            { id: "st-camp-3", workspaceId: "ws-medhit-001", projectId: "proj-campanhas-01", name: "Em Revisão", color: "#f59e0b", position: 3, category: "review" as const },
            { id: "st-camp-4", workspaceId: "ws-medhit-001", projectId: "proj-campanhas-01", name: "Concluído", color: "#22c55e", position: 4, category: "done" as const },
          ],
          sprints: [],
        },
      ],
    },
    {
      name: "Produção Contínuas",
      slug: "producao-continuas",
      description: "Esteiras operacionais contínuas por função: Audiovisual, Design, Social e Copy.",
      icon: "layers",
      color: "#8b5cf6",
      folders: [
        "Audiovisual",
        "Design",
        "Social Mídia",
        "Copywriting",
      ],
      projects: [
        {
          id: "proj-producao-01",
          workspaceId: "ws-medhit-001",
          areaId: "area-2",
          name: "Produção Contínuas",
          slug: "producao-continuas",
          description: "Esteira recorrente de produção por especialista",
          icon: "layers",
          color: "#8b5cf6",
          methodology: "kanban" as const,
          statuses: [
            { id: "st-prod-1", workspaceId: "ws-medhit-001", projectId: "proj-producao-01", name: "A Fazer", color: "#94a3b8", position: 1, category: "todo" as const },
            { id: "st-prod-2", workspaceId: "ws-medhit-001", projectId: "proj-producao-01", name: "Em Andamento", color: "#38bdf8", position: 2, category: "in_progress" as const },
            { id: "st-prod-3", workspaceId: "ws-medhit-001", projectId: "proj-producao-01", name: "Em Revisão", color: "#f59e0b", position: 3, category: "review" as const },
            { id: "st-prod-4", workspaceId: "ws-medhit-001", projectId: "proj-producao-01", name: "Concluído", color: "#22c55e", position: 4, category: "done" as const },
          ],
          sprints: [],
        },
      ],
    },
    {
      name: "Operação Thiago",
      slug: "operacao-thiago",
      description: "Gestão direta de operações estratégicas, alinhamentos e esteiras operacionais.",
      icon: "briefcase",
      color: "#0284c7",
      folders: [
        "Demandas Operacionais",
        "Alinhamentos Executivos",
        "Rotinas Semanais",
      ],
      projects: [
        {
          id: "proj-operacao-01",
          workspaceId: "ws-medhit-001",
          areaId: "area-3",
          name: "Operação Thiago",
          slug: "operacao-thiago",
          description: "Quadro de operação e backlog de execução",
          icon: "briefcase",
          color: "#0284c7",
          methodology: "kanban" as const,
          statuses: [
            { id: "st-op-1", workspaceId: "ws-medhit-001", projectId: "proj-operacao-01", name: "A Fazer", color: "#94a3b8", position: 1, category: "todo" as const },
            { id: "st-op-2", workspaceId: "ws-medhit-001", projectId: "proj-operacao-01", name: "Em Andamento", color: "#38bdf8", position: 2, category: "in_progress" as const },
            { id: "st-op-3", workspaceId: "ws-medhit-001", projectId: "proj-operacao-01", name: "Em Revisão", color: "#f59e0b", position: 3, category: "review" as const },
            { id: "st-op-4", workspaceId: "ws-medhit-001", projectId: "proj-operacao-01", name: "Concluído", color: "#22c55e", position: 4, category: "done" as const },
          ],
          sprints: [],
        },
      ],
    },
    {
      name: "Integrações & Automações",
      slug: "integracoes-e-automacoes",
      description: "Pipelines n8n, Webhooks, Servidor MCP, Supabase e Infraestrutura.",
      icon: "cpu",
      color: "#3b82f6",
      folders: [
        "n8n Pipelines",
        "Datacrazy Webhooks",
        "Servidor MCP",
        "Infraestrutura & DNS",
      ],
      projects: [
        {
          id: "proj-integracoes-01",
          workspaceId: "ws-medhit-001",
          areaId: "area-4",
          name: "Integrações e Automações",
          slug: "integracoes-e-automacoes",
          description: "Quadro de automações n8n, webhooks e esteiras",
          icon: "cpu",
          color: "#3b82f6",
          methodology: "kanban" as const,
          statuses: [
            { id: "st-int-1", workspaceId: "ws-medhit-001", projectId: "proj-integracoes-01", name: "A Fazer", color: "#94a3b8", position: 1, category: "todo" as const },
            { id: "st-int-2", workspaceId: "ws-medhit-001", projectId: "proj-integracoes-01", name: "Em Andamento", color: "#38bdf8", position: 2, category: "in_progress" as const },
            { id: "st-int-3", workspaceId: "ws-medhit-001", projectId: "proj-integracoes-01", name: "Em Revisão", color: "#f59e0b", position: 3, category: "review" as const },
            { id: "st-int-4", workspaceId: "ws-medhit-001", projectId: "proj-integracoes-01", name: "Concluído", color: "#22c55e", position: 4, category: "done" as const },
          ],
          sprints: [],
        },
      ],
    },
  ],
  initialTasks: [] as any[],
};

console.log("MedHit Task Manager Seed Definitions Loaded com sucesso!");
