/**
 * MedHit Task Manager - Seed Script Realista
 * Autor: MedHit Integrações & Automações
 * Gera dados completos para Marketing e Automação com humanos e agentes de IA
 */

export const seedData = {
  workspace: {
    name: "MedHit",
    slug: "medhit",
    settings: {
      theme: "dark",
      aiEnabled: true,
      defaultLanguage: "pt-BR",
    },
  },
  members: [
    {
      name: "Lucca Lagana",
      email: "lucca.guidorizzi@medhit.com.br",
      role: "owner" as const,
      password: "x32kd58",
      mcpToken: "medtask_user_lucca_x32kd58_sec99",
      avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca",
    },
  ],
  agents: [
    {
      name: "MedCopy IA",
      slug: "medcopy-ia",
      role: "Copywriter & Estrategista de Conteúdo",
      model: "gemini-2.0-flash",
      avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=MedCopy",
      description: "Especialista em redação persuasiva para médicos e cursos de saúde.",
      systemPrompt: "Você é um copywriter de elite da MedHit especializado no mercado médico.",
      allowedTools: ["generate_copy", "suggest_headlines", "review_seo"],
      status: "active" as const,
    },
    {
      name: "n8n Auditor IA",
      slug: "n8n-auditor-ia",
      role: "Auditor e Engenheiro de Integrações",
      model: "gemini-2.0-flash",
      avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=n8nAuditor",
      description: "Monitora webhooks, analisa nós n8n e verifica integridade de payloads.",
      systemPrompt: "Você audita e valida fluxos do n8n para a MedHit.",
      allowedTools: ["inspect_workflow", "validate_payload", "report_incident"],
      status: "active" as const,
    },
    {
      name: "Triage Bot IA",
      slug: "triage-bot-ia",
      role: "Triagem Inteligente de Demandas",
      model: "gemini-2.0-flash",
      avatarUrl: "https://api.dicebear.com/7.x/bottts/svg?seed=TriageBot",
      description: "Classifica formulários recebidos e encaminha para a squad correta.",
      systemPrompt: "Você analisa solicitações e sugere prioridade, prazos e responsáveis.",
      allowedTools: ["categorize_request", "assign_team", "estimate_effort"],
      status: "active" as const,
    },
  ],
  areas: [
    {
      name: "Marketing",
      slug: "marketing",
      description: "Campanhas, Conteúdo, Tráfego Pago e Lançamentos MedHit.",
      icon: "megaphone",
      color: "#ec4899",
      projects: [
        {
          id: "proj-marketing-01",
          workspaceId: "ws-medhit-001",
          areaId: "area-1",
          name: "Marketing",
          slug: "marketing",
          description: "Quadro geral de demandas e campanhas de Marketing",
          icon: "megaphone",
          color: "#ec4899",
          methodology: "kanban" as const,
          statuses: [
            { id: "st-mkt-1", workspaceId: "ws-medhit-001", projectId: "proj-marketing-01", name: "A Fazer", color: "#94a3b8", position: 1, category: "todo" as const },
            { id: "st-mkt-2", workspaceId: "ws-medhit-001", projectId: "proj-marketing-01", name: "Em Andamento", color: "#38bdf8", position: 2, category: "in_progress" as const },
            { id: "st-mkt-3", workspaceId: "ws-medhit-001", projectId: "proj-marketing-01", name: "Em Revisão", color: "#f59e0b", position: 3, category: "review" as const },
            { id: "st-mkt-4", workspaceId: "ws-medhit-001", projectId: "proj-marketing-01", name: "Concluído", color: "#22c55e", position: 4, category: "done" as const },
          ],
          sprints: [],
        },
      ],
    },
    {
      name: "Integrações & Automações",
      slug: "integracoes-e-automacoes",
      description: "Pipelines n8n, Webhooks, Integrações CRM e Agentes Autônomos.",
      icon: "cpu",
      color: "#3b82f6",
      projects: [
        {
          id: "proj-integracoes-01",
          workspaceId: "ws-medhit-001",
          areaId: "area-2",
          name: "Integrações e Automações",
          slug: "integracoes-e-automacoes",
          description: "Quadro de automações n8n, webhooks e esteiras",
          icon: "cpu",
          color: "#3b82f6",
          methodology: "kanban" as const,
          statuses: [
            { id: "st-int-1", workspaceId: "ws-medhit-001", projectId: "proj-integracoes-01", name: "A Fazer", color: "#94a3b8", position: 1, category: "todo" as const },
            { id: "st-int-2", workspaceId: "ws-medhit-001", projectId: "proj-integracoes-01", name: "Em Andamento", color: "#38bdf8", position: 2, category: "in_progress" as const },
            { id: "st-int-3", workspaceId: "ws-medhit-001", projectId: "proj-integracoes-01", name: "Em Revisão", color: "#f59e0b", position: 3, category: "review" as const },
            { id: "st-int-4", workspaceId: "ws-medhit-001", projectId: "proj-integracoes-01", name: "Concluído", color: "#22c55e", position: 4, category: "done" as const },
          ],
          sprints: [],
        },
      ],
    },
  ],
  initialTasks: [
    {
      id: "tsk-mkt-01",
      workspaceId: "ws-medhit-001",
      projectId: "proj-marketing-01",
      areaId: "area-1",
      title: "Criar LP /masterclass-ultimasemana1f",
      description: "Construir landing page com captura rápida e pixel do Meta configurado.",
      taskType: "task" as const,
      statusId: "st-mkt-4",
      priority: "high" as const,
      position: 1000,
      tags: ["Masterclass Ultima Semana", "landing-page"],
      assigneeIds: [{ type: "user" as const, id: "user-1", name: "Lucca Lagana", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca" }],
      checklists: [],
      comments: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "tsk-mkt-02",
      workspaceId: "ws-medhit-001",
      projectId: "proj-marketing-01",
      areaId: "area-1",
      title: "Gerar 5 criativos da campanha",
      description: "Criar variações estáticas e carrossel para tráfego pago.",
      taskType: "task" as const,
      statusId: "st-mkt-4",
      priority: "urgent" as const,
      position: 2000,
      tags: ["Masterclass Ultima Semana", "design"],
      assigneeIds: [{ type: "user" as const, id: "user-1", name: "Lucca Lagana", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca" }],
      checklists: [],
      comments: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "tsk-mkt-03",
      workspaceId: "ws-medhit-001",
      projectId: "proj-marketing-01",
      areaId: "area-1",
      title: "Subir campanha Meta no ar",
      description: "Subir anúncios nos conjuntos de público quente e lookalike.",
      taskType: "task" as const,
      statusId: "st-mkt-2",
      priority: "urgent" as const,
      position: 3000,
      tags: ["Masterclass Ultima Semana", "meta-ads"],
      assigneeIds: [{ type: "user" as const, id: "user-1", name: "Lucca Lagana", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca" }],
      checklists: [],
      comments: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "tsk-mkt-04",
      workspaceId: "ws-medhit-001",
      projectId: "proj-marketing-01",
      areaId: "area-1",
      title: "Configurar webhook Datacrazy próprio",
      description: "Conectar formulário com a esteira do n8n e disparos de WhatsApp.",
      taskType: "task" as const,
      statusId: "st-mkt-1",
      priority: "medium" as const,
      position: 4000,
      tags: ["Simulado Intensivo Reta Final", "automacao"],
      assigneeIds: [{ type: "user" as const, id: "user-1", name: "Lucca Lagana", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca" }],
      checklists: [],
      comments: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "tsk-mkt-05",
      workspaceId: "ws-medhit-001",
      projectId: "proj-marketing-01",
      areaId: "area-1",
      title: "Criar grupo WhatsApp da campanha",
      description: "Configurar grupo silencioso e link de redirecionamento dinâmico.",
      taskType: "task" as const,
      statusId: "st-mkt-3",
      priority: "high" as const,
      position: 5000,
      tags: ["Simulado Intensivo Reta Final", "automacao"],
      assigneeIds: [{ type: "user" as const, id: "user-1", name: "Lucca Lagana", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca" }],
      checklists: [],
      comments: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "tsk-int-01",
      workspaceId: "ws-medhit-001",
      projectId: "proj-integracoes-01",
      areaId: "area-2",
      title: "Pipeline de Sincronização Datacrazy -> ActiveCampaign",
      description: "Webhook para ingestão de leads e distribuição de tags.",
      taskType: "task" as const,
      statusId: "st-int-4",
      priority: "urgent" as const,
      position: 1000,
      tags: ["Datacrazy Webhooks", "n8n"],
      assigneeIds: [{ type: "user" as const, id: "user-1", name: "Lucca Lagana", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca" }],
      checklists: [],
      comments: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "tsk-int-02",
      workspaceId: "ws-medhit-001",
      projectId: "proj-integracoes-01",
      areaId: "area-2",
      title: "Auditoria de Nós com Erro no n8n",
      description: "Criar trigger de reprocessamento automático quando houver falha 500.",
      taskType: "task" as const,
      statusId: "st-int-2",
      priority: "high" as const,
      position: 2000,
      tags: ["n8n Pipelines", "auditoria"],
      assigneeIds: [{ type: "user" as const, id: "user-1", name: "Lucca Lagana", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca" }],
      checklists: [],
      comments: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: "tsk-int-03",
      workspaceId: "ws-medhit-001",
      projectId: "proj-integracoes-01",
      areaId: "area-2",
      title: "Configurar Servidor MCP e Endpoints de Automação",
      description: "Integração segura do protocolo MCP com controle de tokens.",
      taskType: "task" as const,
      statusId: "st-int-1",
      priority: "medium" as const,
      position: 3000,
      tags: ["Servidor MCP", "infra"],
      assigneeIds: [{ type: "user" as const, id: "user-1", name: "Lucca Lagana", avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Lucca" }],
      checklists: [],
      comments: [],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
};

console.log("MedHit Task Manager Seed Definitions Loaded com sucesso!");
